### ISSUE TITLE
As a User, I want the color theme to pass accessibility insights assessment in both dark and light mode

### ISSUE THREAD

**Issue by alucernoni** [the-collab-lab/tcl-56-smart-shopping-list#42]
### Summary### 

Adjustments needed to increase contrast between background color and text in the Chippy bubble message, urgency tags, search bar, and (in dark mode) the clickable buttons in the List view. Current color contrast ratios are between ~2.5 to 3.5 and need to be above 4.5 to meet accessibility standards.

### Acceptance Criteria ### 

- [ ] Color contrast in Chippy message bubble needs to be above 4.5. Suggested to use background color: #247aab and the original foreground color: #ffffff to meet a contrast ratio of 4.72:1
- [ ] Color contrast in purchase urgency tags need to be above 4.5. Suggested to use background color: #4477b5 and the original foreground color: #ffffff to meet a contrast ratio of 4.61:1.
- [ ] Color contrast in search bar needs to be above 4.5. Suggested to use foreground color: #8caddc and the original background color: #3b3b3b to meet a contrast ratio of 4.87:1.
- [ ] Color contrast in Add Item, Click Here, and Clear buttons needs to be above 4.5. Suggested to use foreground color: #3098ff and the original background color: #282c34 to meet a contrast ratio of 4.71:1.
- [ ] Run accessibility insights extension in both light and dark mode to ensure that the 4.5+ color contrast accessibility standard is being met

### Notes ### 

The Click Here, Add Item, and Clear buttons shift colors upon hovering. We likely want to update these hovering color schemes as well to ensure that the hovering colors also meet accessibility color contrast standards (4.5+).
